In [1]:
from support_assistant.analysis import load_tickets,count_by,high_priority,top_words

from support_assistant.data import load_tickets as load_df

tickets = load_tickets("/Users/mac/Desktop/2026/Bootcamp/code/support-assistant/data/sample/ticket.csv")
df = load_df("/Users/mac/Desktop/2026/Bootcamp/code/support-assistant/data/sample/ticket.csv")

In [2]:
type(df)

pandas.DataFrame

In [3]:
df.shape

(12, 7)

In [4]:
list(df.columns)

['id', 'created_at', 'channel', 'category', 'priority', 'subject', 'body']

In [5]:
df.head(3)

,id,created_at,channel,category,priority,subject,body
0,T-1001,2026-09-01,email,billing,high,Charged twice this month,"I was billed twice on 1 September, please refu..."
1,T-1002,2026-09-01,chat,login,medium,Cannot reset password,The reset link in the email expires before I c...
2,T-1003,2026-09-02,web,shipping,low,Where is my order,Tracking has not updated in four days

In [6]:
df["category"]

0             billing
1               login
2            shipping
3                 bug
4     feature_request
5             billing
6               login
7            shipping
8                 bug
9             billing
10    feature_request
11              login
Name: category, dtype: str

In [7]:
type(df["category"])

pandas.Series

In [8]:
df["category"][0]

'billing'

In [9]:
df["category"].value_counts()

category
billing            3
login              3
shipping           2
bug                2
feature_request    2
Name: count, dtype: int64

In [10]:
df["category"].value_counts().to_dict()

{'billing': 3, 'login': 3, 'shipping': 2, 'bug': 2, 'feature_request': 2}

In [12]:
count_by(tickets,"category")

{'billing': 3, 'login': 3, 'shipping': 2, 'bug': 2, 'feature_request': 2}

In [13]:
df["category"].value_counts().to_dict() == count_by(tickets, "category")

True

In [14]:
df["priority"] == "high"

0      True
1     False
2     False
3      True
4     False
5     False
6      True
7     False
8     False
9     False
10    False
11    False
Name: priority, dtype: bool

In [15]:
df[df["priority"] == "high"]

,id,created_at,channel,category,priority,subject,body
0,T-1001,2026-09-01,email,billing,high,Charged twice this month,"I was billed twice on 1 September, please refu..."
3,T-1004,2026-09-02,email,bug,high,App crashes on export,Exporting a report to PDF closes the app every...
6,T-1007,2026-09-04,web,login,high,Locked out after 2FA change,Changed phones and now 2FA codes are rejected

In [16]:
df[df["priority"] == "high"] ["id"].tolist()

['T-1001', 'T-1004', 'T-1007']

In [17]:
[t.id for t in high_priority(tickets)]

['T-1001', 'T-1004', 'T-1007']

In [20]:
df[(df["channel"] == "email") & (df["priority"] == "medium")]["id"].tolist()

['T-1006', 'T-1009']

In [23]:
df.groupby("category").size()

category
billing            3
bug                2
feature_request    2
login              3
shipping           2
dtype: int64

In [24]:
df.groupby(["channel","priority"]).size()

channel  priority
chat     low         1
         medium      3
email    high        2
         low         1
         medium      2
web      high        1
         low         2
dtype: int64

In [25]:
df["subject"].str.lower().str.split()

0         [charged, twice, this, month]
1             [cannot, reset, password]
2                [where, is, my, order]
3            [app, crashes, on, export]
4                  [dark, mode, please]
5       [invoice, missing, vat, number]
6     [locked, out, after, 2fa, change]
7              [wrong, item, delivered]
8        [search, returns, no, results]
9               [update, card, details]
10                  [export, to, excel]
11         [email, change, not, saving]
Name: subject, dtype: object

In [31]:
df["subject"].str.lower().str.split().explode()

0       charged
0         twice
0          this
0         month
1        cannot
1         reset
1      password
2         where
2            is
2            my
2         order
3           app
3       crashes
3            on
3        export
4          dark
4          mode
4        please
5       invoice
5       missing
5           vat
5        number
6        locked
6           out
6         after
6           2fa
6        change
7         wrong
7          item
7     delivered
8        search
8       returns
8            no
8       results
9        update
9          card
9       details
10       export
10           to
10        excel
11        email
11       change
11          not
11       saving
Name: subject, dtype: str

In [32]:
df["subject"].str.lower().str.split().explode().value_counts()

subject
export       2
change       2
charged      1
twice        1
this         1
month        1
cannot       1
reset        1
password     1
where        1
is           1
my           1
order        1
app          1
crashes      1
on           1
dark         1
mode         1
please       1
invoice      1
missing      1
vat          1
number       1
locked       1
out          1
after        1
2fa          1
wrong        1
item         1
delivered    1
search       1
returns      1
no           1
results      1
update       1
card         1
details      1
to           1
excel        1
email        1
not          1
saving       1
Name: count, dtype: int64

In [33]:
df["subject"].str.lower().str.split().explode().value_counts().head(3)

subject
export     2
change     2
charged    1
Name: count, dtype: int64

In [34]:
top_words(tickets)

[('export', 2), ('change', 2), ('charged', 1)]

In [35]:
df["created_at"].dtype

dtype('<M8[us]')

In [38]:
df["created_at"].min(), df["created_at"].max()

(Timestamp('2026-09-01 00:00:00'), Timestamp('2026-09-06 00:00:00'))

In [44]:
df["created_at"].dt.date

0     2026-09-01
1     2026-09-01
2     2026-09-02
3     2026-09-02
4     2026-09-03
5     2026-09-03
6     2026-09-04
7     2026-09-04
8     2026-09-05
9     2026-09-05
10    2026-09-06
11    2026-09-06
Name: created_at, dtype: object

In [45]:
df.groupby(df["created_at"].dt.date).size()

created_at
2026-09-01    2
2026-09-02    2
2026-09-03    2
2026-09-04    2
2026-09-05    2
2026-09-06    2
dtype: int64